apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcereservations.scheduling.kubenexus.io
spec:
  group: scheduling.kubenexus.io
  names:
    kind: ResourceReservation
    listKind: ResourceReservationList
    plural: resourcereservations
    singular: resourcereservation
    shortNames:
      - rr
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - reservations
              properties:
                reservations:
                  type: object
                  additionalProperties:
                    type: object
                    required:
                      - node
                      - cpu
                      - memory
                    properties:
                      node:
                        type: string
                        description: The name of the node where resources are reserved
                      cpu:
                        type: string
                        pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$'
                        description: The amount of CPU reserved (e.g., "1", "1000m", "2.5")
                      memory:
                        type: string
                        pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$'
                        description: The amount of memory reserved (e.g., "1Gi", "512Mi", "2048Mi")
            status:
              type: object
              properties:
                pods:
                  type: object
                  additionalProperties:
                    type: string
                  description: Maps pod names to their current state
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
